# Generated by Django 5.2.6 on 2025-09-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registration_delete_registation'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(default='Not specified', max_length=50),
        ),
    ]
